### ISSUE TITLE
**ROADMAP**

### ISSUE THREAD

**Issue by dcts** [dcts/instagram-bot-nodeJS#4]
**MILESTONES**
- [ ] **run script for a given user**
  - [x] **V1**: scrape all messages of this user (for new users)
  - [ ] **V2**: add last added item so that not all messages get loaded, only the last few (for existing users)

- [ ] **do not load already added items**:
  - [ ] **V1**: load messages until the point where we replied
  - [ ] **V2**: initialize database where for each user the id of the last added item is stored
    - [ ] simple: store inside file
    - [ ] advanced: store in firebase: 

- [ ] **run script for subset of known users**: lets pick the top 10 listers and start testing with them before adding all users. 
  - [ ] if user exists: lookup last added `itemId`, run algorithm, update last added `itemId`
  - [ ] if user new: run algorithm, initialize last added `itemId`

- [ ] **run the script for all users**
  - [ ] manually adding items: ?? (not sure how to keep track of last added items

### Things that need to be done ordered by imprtance:
- [ ] **`Promise.all`**: wait for all items to be saved to firebase before changing the `itemIds` array inside the list object. 
- [ ] **last item**: implement function that stops loading messages once a give `message_id` is reached.
- [ ] **last item**: find out if you can access the `message_id` somehow with the profile name, such that it becomes easy to transform the place/profile name into a `message_id`. To manually add items.
- [ ] find out if pending DM requests will still be loaded when grabbing all unread threads

**Comment by dcts** [comment]
errors:
- [ ] ordering of items not correct -> ensure with `promises` `.then()` ...
